//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroUsuarios1._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuarios
    {
        public int id_usuario { get; set; }
        public string nombre_usuario { get; set; }
        public string apellidoP_usuario { get; set; }
        public string apellidoM_usuario { get; set; }
        public Nullable<int> edad_usuario { get; set; }
        public string clv_elec_usuario { get; set; }
        public string curp_usuario { get; set; }
        public Nullable<int> anio_reg_usuario { get; set; }
        public string estado_usuario { get; set; }
        public string municipio_usuario { get; set; }
        public Nullable<int> seccion_usuario { get; set; }
        public string localidad_usuario { get; set; }
        public Nullable<int> emicion_usuario { get; set; }
        public Nullable<int> vigencia_usuario { get; set; }
        public string perfil_usuario { get; set; }
    }
}
